apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "streambridge.fullname" . }}
  labels:
    app: streambridge
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: streambridge
  template:
    metadata:
      labels:
        app: streambridge
    spec:
      containers:
        - name: kafka-connect
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 8083
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
